# -*- coding: utf-8 -*-
"""AI generated text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Whj4Hp-S5ucvNlRggyNOQqyRPZzmPiIE
"""

from transformers import pipeline
generator = pipeline('text-generation', model='gpt2')
prompt="Artificial Intelligence in finance will"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])