# -*- coding: utf-8 -*-
"""Meeting Minutes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zz3i2tNxGxUtZ0CFshcKznfenE6hZmUd
"""

import pandas as pd
from datetime import datetime
print("MEETING MINUTES GENERATOR\n")
meeting_title=input("enter meeting title: ")
date=input("enter meeting date: ")
time=input("enter meeting time:")
participants=input("enter participants(comma seperated):")
agenda=input("enter agenda points(comma seperated):")
decisions=input("enter decisions(comma seperated):")
action_items=input("enter action items(comma seperated):")
prepared_by=input("prepared by:")
participants_list=[p.strip() for p in participants.split(",")if p.strip()]
agenda_list=[a.strip() for a in agenda.split(",")if a.strip()]
decisions_list=[d.strip()for d in decisions.split(",")if d.strip()]
actions_list=[a.strip()for a in action_items.split(",")if a.strip()]
minutes={
    "Meeting Title":meeting_title,
    "Date":date,
    "Time":time,
    "Participants":",".join(participants_list),
    "Agenda":";".join(agenda_list),
    "Decisions Taken":";".join(decisions_list),
    "Action Items":";".join(actions_list),
    "Prepared By":prepared_by,
    "Generated on":datetime.now().strftime("%Y-%m-%d %H:%M:%S")
}
df=pd.DataFrame(list(minutes.items()),columns=["Field","Details"])
print("\n Meeting Minutes Generated successfully\n")
display(df)
df.to_csv("meeting_minutes.csv",index=False)
print("Minutes saved to meeting_minutes.csv")

