# -*- coding: utf-8 -*-
"""product  review analyser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7qXJ1QtNrQcBFb3kKru072VtmGzjKII
"""

!pip install transformers
  from transformers import pipeline
  import pandas as pd

sentiment=pipeline("sentiment-analysis")
reviews="""the laptop starts quickly and works smoothly for daily tasks.
the screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
the fan makes noise when many apps are running.
overall,it is a good laptop forstudents but not for gaming.
"""
sentences=reviews.split(".")
pros=[]
cons=[]
for s in sentences:
  s=s.strip()
  if s =="":
    continue
  result=sentiment(s)[0]
  if result["label"]=="POSITIVE":
    pros.append(s)
  elif result["label"]=="NEGATIVE":
    cons.append(s)
pros=pros[:2]
cons=cons[:2]
df=pd.DataFrame({
    "Pros":pros,
    "Cons":cons
})
df