# -*- coding: utf-8 -*-
"""SentenceSimilarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5gRBhdTswvxgIO0BdEV_A5rUFDELGE5
"""

from sentence_transformers import SentenceTransformer, util

# Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Take input from user
text1 = input("Enter text 1: ")
text2 = input("Enter text 2: ")

# Convert text to embeddings
embeddings1 = model.encode(text1)
embeddings2 = model.encode(text2)

# Calculate similarity
similarity = util.cos_sim(embeddings1, embeddings2)

#Show result
print("\nSimilarity Score:", round(float(similarity), 2))
if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.5:
  print("Similarity Level: Medium")
else:
  print("Similarity Level: Low")